common_fields: &common_fields
      - label: "URL标识符"
        name: "slug"
        widget: "string"
        required: true
        hint: "示例：how-to-use-decap-cms (至少7个字符)"
        pattern: 
          - "^[a-z0-9-]{8,}$"
          - "必须满足：1) 只含:全小写英文/数字/横线 2) 至少8个字符"
        error_messages:
          required: "❗必须填写URL永久链接标识符"
          pattern: "❗格式错误：只能包含小写字母、数字、横线，且至少8个字符"
      - label: '标题'
        name: 'title'
        widget: 'string'
        required: true
        error_messages:
          required: "❗必须填写,作为文章核心搜索标识.."
      - label: '发布日期'
        name: 'date'
        widget: 'datetime'
        required: true
        error_messages:
          required: "❗必须填写,作为文章关键线索信息.."
      - label: '描述'
        name: 'description'
        widget: 'description'
        required: true
        error_messages:
          required: "❗必须填写,作为内容宣传关键摘要.."
      - { label: "草稿?", name: "draft", widget: "boolean",default: true, hint: "草稿状态的文章不会被公开.." }
      - { label: "摘要", name: "summary", widget: "text" }
      - { label: '显示作者?', name: 'showAuthor', widget: 'boolean', default: true }
      - {
          label: '作者',
          name: 'authors',
          widget: 'select',
          multiple: true,
          default: ["fmclub"],
          options: ["fmclub", "zoomquiet"],
          hint: '联系大妈配置更多作者',
        }
      - { 
          label: "封面图片", 
          name: "cover", 
          widget: "image", 
          media_library: {
            config: {
              multiple: false
            }
          },
          hint: "必须是 cover.png|jpg|webp",
          pattern: ["^cover\\.(png|jpg|jpeg|webp)$", "文件必须命名为 cover.png/cover.jpg 最好是 cover.webp"],
        }
      - { 
        label: '标签', 
        name: 'tags', 
        widget: 'list', 
        allow_add: true,
        hint: '内容要点, 例如：Hugo, DecapCMS, Markdown',
        }

backend:
  name: github
  repo: Makeplayism/hugo
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://www.makeplay.us
  auth_endpoint: /api/auth
media_folder: static/img
public_folder: /img
collections:
  - name: 'Posts'
    label: '文章'
    label_singular: '文章'
    folder: 'content/posts'
    create: true
    path: "{{fields.slug}}/index"
    slug: '{{year}}-{{month}}-{{day}}-{{fields.slug}}'
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - <<: *common_fields
      - { 
        label: '分类', 
        name: 'categories', 
        widget: 'select', 
        multiple: false,
        default: ["Post"],
        options: ["Post","Blog"],
        allow_add: true,
        hint: '内容类型',
        }
      - { label: "正文", name: "body", widget: "markdown" }
  - name: 'Pages'
    label: "关于"
    label_singular: 'Pages'
    folder: "content/pages"
    create: true
    path: "{{fields.slug}}/index"
    media_folder: '{{fields.slug}}'
    public_folder: '/pages/{{fields.slug}}'
    editor:
      preview: false
    fields:
      - <<: *common_fields
      - { 
        label: '分类', 
        name: 'categories', 
        widget: 'select', 
        multiple: false,
        default: ["LOG"],
        options: ["LOG","ANN","DOC"],
        allow_add: true,
        hint: '内容类型',
        }
      - { label: "正文", name: "body", widget: "markdown" }
  - name: 'Events'
    label: "活动"
    label_singular: 'Events'
    folder: "content/events"
    create: true
    path: "{{fields.slug}}/index"
    media_folder: '{{fields.slug}}'
    public_folder: '/events/{{fields.slug}}'
    editor:
      preview: false
    fields:
      - <<: *common_fields
      - { 
        label: '分类', 
        name: 'categories', 
        widget: 'select', 
        multiple: false,
        default: ["LOCAL"],
        options: ["LOCAL","ONLINE","MOVIE","DISCUSSION","BUILDING","MAKING","READING"],
        allow_add: true,
        hint: '内容类型',
        }
      - { label: "正文", name: "body", widget: "markdown" }
  - name: 'Projects'
    label: "项目"
    label_singular: 'Projects'
    folder: "content/projects"
    create: true
    path: "{{fields.slug}}/index"
    media_folder: '{{fields.slug}}'
    public_folder: '/projects/{{fields.slug}}'
    editor:
      preview: false
    fields:
      - <<: *common_fields
      - { 
        label: '分类', 
        name: 'categories', 
        widget: 'select', 
        multiple: false,
        default: ["LOCAL"],
        options: ["LOCAL","ONLINE","MOVIE","DISCUSSION","BUILDING","MAKING","READING"],
        allow_add: true,
        hint: '项目类型',
        }
      - { label: "正文", name: "body", widget: "markdown" }
  - name: 'Authors'
    label: "作者"
    label_singular: 'Authors'
    folder: "content/authors"
    create: true
    path: "{{fields.slug}}/index"
    media_folder: '{{fields.slug}}'
    public_folder: '/authors/{{fields.slug}}'
    editor:
      preview: false
    fields:
      - <<: *common_fields
      - { 
        label: '分类', 
        name: 'categories', 
        widget: 'select', 
        multiple: false,
        default: ["MAKER"],
        options: ["MAKER","GEEK","NERD","SEEKER","THINKER","WRITER","READER","DOGE","CATS","FISH","BIRD"],
        allow_add: true,
        hint: '人物类型',
        }
      - { label: "正文", name: "body", widget: "markdown" }
